name: Farm Assistant
version: "0.7.8"
slug: farm_assistant
description: "An addon to manage your farm's livestock data."
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:barn
panel_title: Farm Assistant
ingress: true
ingress_port: 8000
ingress_stream: true
uart: false
options:
  db_host: ""
  db_port: 5432
  db_user: ""
  db_password: ""
  db_name: ""
schema:
  db_host: str
  db_port: int
  db_user: str
  db_password: password
  db_name: str
