name: Farm Assistant
version: "1.11.26"
slug: farm_assistant
description: "An addon to manage your farm's livestock data."
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:barn
panel_title: Farm Assistant
ingress: true
ingress_port: 8000
ingress_stream: true
uart: false
options:
  db_host: "192.168.1.130"
  db_port: 5432
  db_user: "postgres"
  db_password: "homeassistant"
  db_name: "hal_farm_db"
schema:
  db_host: str
  db_port: int
  db_user: str
  db_password: password
  db_name: str
